name: Push_workflow
on:
    push:
        branches:
            - main
            - qa

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: First auto push
              run: echo "auto push"
            - name: 2nd auto push
              run: | 
                  echo "first"
                  echo "second"

